name: smn_tools
channels:
  - conda-forge
dependencies:
  - python=3.10
  - xarray>=2023.7.0
  - numpy>=1.24.3
  - pandas>=2.0.3
  - netCDF4>=1.6.2
  - h5netcdf>=1.2.0
  - h5py>=3.8.0
  - cfgrib>=0.9.10.4
  - eccodes>=2.27.0
  - pip
  - pip:
      - -e .

